2018-10-10 12:52:57 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:52:57 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:53:06 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:53:06 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:56:36 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:56:36 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:56:36 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:56:36 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:56:37 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:56:37 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:56:37 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:56:37 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:56:38 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:56:38 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:56:38 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:56:38 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:56:38 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:56:38 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:56:38 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 29]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:56:38 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 29
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:57:19 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:57:19 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 30
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:57:20 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:57:20 Error: [Cake\Error\FatalErrorException] Trait 'App\View\UIViewTrait' not found in C:\xampp\htdocs\labtig\src\View\AppView.php on line 30
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2018-10-10 12:58:50 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:58:50 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUi()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 12:58:50 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUi()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 12:59:02 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /labtig/debug-kit/toolbar/11595407-4ce2-4c19-bf1d-c624a46c0e42
Referer URL: http://localhost/labtig/labtig/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:59:02 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUi()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 12:59:02 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUi()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 12:59:13 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:59:13 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUi()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 12:59:13 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUi()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 12:59:45 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:59:45 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 12:59:45 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 12:59:47 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 12:59:47 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 12:59:47 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:07 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:07 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:07 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:08 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:08 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:08 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:09 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:10 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:10 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:10 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:10 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:10 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:10 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:10 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:10 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:10 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:10 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:10 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:10 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:11 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:11 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:11 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:11 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:11 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:11 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:11 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:11 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:11 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:11 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:11 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:11 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:12 Error: Fatal Error (1): Trait 'App\View\UIViewTrait' not found in [C:\xampp\htdocs\labtig\src\View\AppView.php, line 30]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 229
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 109
[main] - [internal], line ??



2018-10-10 13:02:12 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#10 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#11 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:02:12 Error: Fatal Error (256): [Error] Call to undefined method App\View\AppView::initializeUI()
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\View.php(371): App\View\AppView->initialize()
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewBuilder.php(640): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager), Array)
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php(123): Cake\View\ViewBuilder->build(Array, Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Event\EventManager))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Controller\Controller.php(789): Cake\Controller\Controller->createView()
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Controller\Controller->render('fatalError')
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(205): Cake\Error\ExceptionRenderer->_outputMessage('fatalError')
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(139): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180)
#10 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\config\bootstrap.php(42): Cake\Error\BaseErrorHandler->handleError(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#11 [internal function]: Cake\Core\BasePlugin->{closure}(256, '[Error] Call to...', 'C:\\xampp\\htdocs...', 180, Array)
#12 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(180): trigger_error('[Error] Call to...', 256)
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(141): Cake\Error\ErrorHandler->_logInternalError(Object(Error))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(193): Cake\Error\ErrorHandler->_displayException(Object(Error))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(231): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#16 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(109): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Trait 'App\\View...', 'C:\\xampp\\htdocs...', 30)
#17 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#18 {main} in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 180]


2018-10-10 13:40:25 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:40:29 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:41:46 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:42:45 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:43:04 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:43:58 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/jquery-3.1.1.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:43:58 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:44:38 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/jquery-3.1.1.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:44:38 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:44:39 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/jquery-3.1.1.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:44:39 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:45:11 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:45:42 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/adminlte.min.js
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:49:27 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Img could not be found.
Exception Attributes: array (
  'class' => 'Img',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /img/avatar5.png
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:49:41 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Img could not be found.
Exception Attributes: array (
  'class' => 'Img',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /img/avatar5.png
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:50:10 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Img could not be found.
Exception Attributes: array (
  'class' => 'Img',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /img/avatar5.png
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:50:12 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Img could not be found.
Exception Attributes: array (
  'class' => 'Img',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /img/avatar5.png
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:50:24 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Img could not be found.
Exception Attributes: array (
  'class' => 'Img',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /img/avatar5.png
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 13:50:26 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Img could not be found.
Exception Attributes: array (
  'class' => 'Img',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /img/avatar5.png
Referer URL: http://localhost/labtig/index
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(97): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 14:14:52 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Otro could not be found.
Exception Attributes: array (
  'class' => 'Otro',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /otro
Stack Trace:
#0 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(39): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(91): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\labtig\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\labtig\webroot\index.php(40): Cake\Http\Server->run()
#17 {main}


2018-10-10 15:33:53 Warning: Warning (512): Unable to emit headers. Headers sent in file=C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Debugger.php line=853 in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 48]
Request URL: /mapconfig
Referer URL: http://localhost/labtig/mapconfig
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 159
Cake\Core\BasePlugin::{closure}() - ROOT\vendor\cakephp\debug_kit\config\bootstrap.php, line 42
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 48
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 141
[main] - ROOT\webroot\index.php, line 40



2018-10-10 15:33:53 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Debugger.php:853) in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 148]
Request URL: /mapconfig
Referer URL: http://localhost/labtig/mapconfig
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 159
Cake\Core\BasePlugin::{closure}() - ROOT\vendor\cakephp\debug_kit\config\bootstrap.php, line 42
header - [internal], line ??
Cake\Http\ResponseEmitter::emitStatusLine() - CORE\src\Http\ResponseEmitter.php, line 148
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 54
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 141
[main] - ROOT\webroot\index.php, line 40



2018-10-10 15:33:53 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Debugger.php:853) in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /mapconfig
Referer URL: http://localhost/labtig/mapconfig
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 159
Cake\Core\BasePlugin::{closure}() - ROOT\vendor\cakephp\debug_kit\config\bootstrap.php, line 42
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 141
[main] - ROOT\webroot\index.php, line 40



2018-10-10 15:33:53 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Error\Debugger.php:853) in [C:\xampp\htdocs\labtig\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /mapconfig
Referer URL: http://localhost/labtig/mapconfig
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 159
Cake\Core\BasePlugin::{closure}() - ROOT\vendor\cakephp\debug_kit\config\bootstrap.php, line 42
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 141
[main] - ROOT\webroot\index.php, line 40



